CoreMVC/WebCoreMVC/WebCoreMVC/Controllers/EntityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebCoreMVC.Models;
using WebCoreMVC.Models.DBContext;
using WebCoreMVC.Models.DBModels;

namespace WebCoreMVC.Controllers
{
    public class EntityController : Controller
    {
        private MobileContext db;
        public EntityController(MobileContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await db.Users.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            db.Users.Add(user);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                User user = await db.Users.FirstOrDefaultAsync(p => p.Id == id);
                if (user != null)
                    return View(user);
            }
            return NotFound();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                User user = await db.Users.FirstOrDefaultAsync(p => p.Id == id);
                if (user != null)
                    return View(user);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Update(user);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            {
                return View(user);
            }
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                User user = await db.Users.FirstOrDefaultAsync(p => p.Id == id);
                if (user != null)
                    return View(user);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int? DeleteId)
        {
            if (ModelState.IsValid && DeleteId != null)
            {
                User user = await db.Users.FirstOrDefaultAsync(p => p.Id == DeleteId);
                if (user != null)
                {
                    db.Users.Remove(user);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Sort(SortState sortOrder = SortState.NameAsc, int page = 1)
        {
            //int pageSize = 2;
            //IQueryable<User> users = db.Users.Include(x => x.Company);

            //users = sortOrder switch
            //{
            //    SortState.NameDesc => users.OrderByDescending(s => s.Name),
            //    SortState.AgeAsc => users.OrderBy(s => s.Age),
            //    SortState.AgeDesc => users.OrderByDescending(s => s.Age),
            //    SortState.CompanyAsc => users.OrderBy(s => s.Company.Name),
            //    SortState.CompanyDesc => users.OrderByDescending(s => s.Company.Name),
            //    _ => users.OrderBy(s => s.Name),
            //};

            //var count = await users.CountAsync();
            //var items = await users.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            //PageViewModel pageVM = new PageViewModel(count, page, pageSize);

            SortViewModel viewModel = new SortViewModel();
            //{
            //    Users = items,
            //    SortUsersModel = new SortUsersModel(sortOrder),
            //    PageViewModel = pageVM
            //};
            return View(viewModel);
        }
    }
}

CoreMVC/WebCoreMVC/WebCoreMVC/Views/Entity/Create.cshtml
@model WebCoreMVC.Models.DBModels.User
@{
    ViewBag.Title = "Добавление пользователя";
}
<form asp-action="create" asp-controller="Entity">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Имя</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Age" class="control-label">Возраст</label>
        <input type="number" asp-for="Age" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

CoreMVC/WebCoreMVC/WebCoreMVC/Views/Entity/Delete.cshtml
@model WebCoreMVC.Models.DBModels.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        @Html.Hidden("DeleteId", Model.Id)
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CoreMVC/WebCoreMVC/WebCoreMVC/Views/Entity/Details.cshtml
@model WebCoreMVC.Models.DBModels.User

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Удалить", "Delete", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

CoreMVC/WebCoreMVC/WebCoreMVC/Views/Entity/Edit.cshtml
@model WebCoreMVC.Models.DBModels.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

CoreMVC/WebCoreMVC/WebCoreMVC/Views/Entity/Entity.cshtml
@model WebCoreMVC.Models.DBModels.User
@{
    ViewBag.Title = "Добавление пользователя";
}
<form asp-action="create" asp-controller="home">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Имя</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Age" class="control-label">Возраст</label>
        <input type="number" asp-for="Age" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

CoreMVC/WebCoreMVC/WebCoreMVC/Views/Entity/Index.cshtml
@model IEnumerable<WebCoreMVC.Models.DBModels.User>
@{
    ViewBag.Title = "Все пользователи";
}
<a asp-action="Create">Добавить пользователя</a>
<table class="table">
    <tr><td>Имя</td><td>Возраст</td></tr>
    @foreach (var item in Model)
    {
        <tr><td>@item.Name</td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

CoreMVC/WebCoreMVC/WebCoreMVC/Views/Entity/Sort.cshtml
@using WebCoreMVC.Models
@using WebCoreMVC.Models.DBModels

@model SortViewModel
<!--импортируем tag-хелперы проекта-->
@addTagHelper *, SortApp

@{
    ViewData["Title"] = "Список пользователей";
}
<style>
    @@font-face {
        font-family: 'FontAwesome';
        src: url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2') format('woff2'), url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff') format('woff'), url('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/fonts/fontawesome-webfont.ttf') format('truetype');
        font-weight: normal;
        font-style: normal
    }

    .glyphicon {
        display: inline-block;
        font: normal normal normal 14px/1 FontAwesome;
        font-size: inherit;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale
    }

    .glyphicon-chevron-down:before {
        content: "\f078";
    }

    .glyphicon-chevron-up:before {
        content: "\f077";
    }
</style>
<h1>Список пользователей</h1>
<table class="table">
    <tr>
        <th>
            <sort-header action="Sort" up="@Model.SortUsersModel.Up"
                         current="@Model.SortUsersModel.Current" property="@Model.SortUsersModel.NameSort">
                Имя
            </sort-header>
        </th>
        <th>
            <sort-header action="Sort" up="@Model.SortUsersModel.Up"
                         current="@Model.SortUsersModel.Current" property="@Model.SortUsersModel.AgeSort">
                Возраст
            </sort-header>
        </th>
        <th>
            <sort-header action="Sort" up="@Model.SortUsersModel.Up"
                         current="@Model.SortUsersModel.Current" property="@Model.SortUsersModel.CompanySort">
                Компания
            </sort-header>
        </th>
    </tr>
    @*@foreach (User u in Model.Users)
    {
        <tr><td>@u.Name</td><td>@u.Age</td><td>@u.Company.Name</td></tr>
    }*@
</table>
<page-link page-model="Model.PageViewModel" page-action="Sort"></page-link>